config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :users

  resources :events do
    post :check, on: :collection
    post :check, on: :member

    get :register, to: "registrations#new"
    post :register, to: "registrations#create"

    resource  :registration, only: [:show, :update] do
      get :summary
    end
    resource :itinerary do
      post :check
    end
    resources :registrations, shallow: true
    resource  :timetable
    resources :activities
    resources :activity_types, only: [:create, :update, :destroy]
    resources :time_slots, only: [:create, :destroy]
    resources :scheduled_activities, only: [:create, :update, :destroy]
    resources :locations
    resources :payments do
      post :approve, on: :collection
      post :decline, on: :collection
    end
    resources :participants do
      resource :itinerary do
        post :check
      end
    end
    
    post "payments/:id", to: "payments#show" # PayPal POSTs this request
    
    resource  :account
    resource  :map, only: :show
  end
  
  post "events/:event_id/payments/:id/process",
    to: "payments#process_external_payment",
    as: :process_external_payment

  root to: "events#index"
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :load_event
  before_action :authorize_for_event_updates

  def index
    @participants = ListParticipants.new(@event, params).call
  end
  
  protected
  
  def load_event
    @event = Event.find_by!(slug: params[:event_id])
  end
  
  def authorize_for_event_updates
    authorize!(:update, @event)
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_participant.html.erb
<%= content_tag(:tr, "data-id" => participant.id) do %>
  <td><%= link_to participant.user.name, event_participant_path(@event, participant), class: "name" %></td>
  <td><%= mail_to participant.user.email %></td>
  <td>
    <%= link_to t("participants.itinerary"), event_participant_itinerary_path(@event, participant.user.id), class: "button" %>
  </td>
<% end -%>

app/views/participants/index.html.erb
<div class="participants-list">
  <header>
    
  </header>
  <div class="table-container">
    <div class="table-and-footer" id="table">
      <div class="scrolling-table">
        <table>
          <thead>
            <tr>
              <th><%= User.human_attribute_name(:name) %></th>
              <th><%= User.human_attribute_name(:email) %></th>
              <th><%= t("participants.actions") %>
            </tr>
          </thead>
          <tbody>
            <%= render(partial: "participant", collection: @participants) %>
          </tbody>
        </table>
      </div>
      <footer>
        <%= will_paginate @participants, inner_window: 2, outer_window: 0 %>
      </footer>
    </div>
  </div>
</div>