config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :users

  resources :events do
    post :check, on: :collection
    post :check, on: :member

    get :register, to: "registrations#new"
    post :register, to: "registrations#create"

    resource  :registration, only: [:show, :update] do
      get :summary
    end
    resource :itinerary do
      post :check
    end
    resources :registrations, shallow: true
    resource  :timetable
    resources :activities
    resources :activity_types, only: [:create, :update, :destroy]
    resources :time_slots, only: [:create, :destroy]
    resources :scheduled_activities, only: [:create, :update, :destroy]
    resources :locations
    resources :payments do
      post :approve, on: :collection
      post :decline, on: :collection
    end
    resources :participants do
      resource :itinerary do
        post :check
      end
    end
    
    post "payments/:id", to: "payments#show" # PayPal POSTs this request
    
    resource  :account
    resource  :map, only: :show
  end
  
  post "events/:event_id/payments/:id/process",
    to: "payments#process_external_payment",
    as: :process_external_payment

  root to: "events#index"
end

app/views/shared/_header.html.erb
<header class="page-header">
  <label for="show-sidebar">
    <%= icon :menu %>
  </label>
  <%= event_header_link %>
</header>

app/views/shared/_sidebar.html.erb
<%= hidden_field_tag(:event_id, event.to_param) if respond_to?(:event) %>
<input type="checkbox" id="show-sidebar" autocomplete="off" tabindex="-1">
<label class="scrim" for="show-sidebar"></label>
<aside class="sidebar">
  <header>
    <% if signed_in? -%>
      <%= avatar current_user %>
      <%= popup_menu current_user_details do %>
        <%= action_list do -%>
          <%= action_list_item t("helpers.submit.session.destroy"), destroy_user_session_path, "logout", method: :delete %>
        <% end -%>
      <% end -%>
    <% else -%>
      <%= form_for User.new, url: session_path(:user) do |form| -%>
        <%= form.email_field :email, placeholder: t("helpers.label.user.email") %>
        <%= form.password_field :password, placeholder: t("helpers.label.user.password") %>
        <%= form.hidden_field :remember_me, value: 1 %>
        <%= link_to t("accounts.forgot_password"), new_user_password_path %>
        <footer>
          <%= form.button do -%>
            <span><%= t("helpers.submit.session.create") %></span>
          <% end -%>
          <%= action_list do %>
            <%= action_list_item t("accounts.sign_up"), new_user_registration_path, "sign-up" %>
          <% end -%>
        </footer>
      <% end -%>
    <% end -%>
  </header>

  <% with_current_event do |event| -%>
    <%= content_tag :section, class: "current-event" do %>
      <%= content_tag :h4, event.name %>
      <div class="registration">
        <%= loading_spinner %>
      </div>
      <% if can? :update, event -%>
        <h4><%= t("events.admin_menu", event: event.name) %></h4>
        <%= action_list do -%>
          <%= action_list_item(t("events.participants"), event_participants_path(event), "participants") %>
          <%= action_list_item(t("events.edit_settings"), edit_event_path(event), "settings") %>
          <%= action_list_item(t("events.edit_timetable"), edit_event_timetable_path(event), "timetable") %>
        <% end -%>
      <% end -%>
    <% end -%>
  <% end -%>

  <section>
    <%= action_list do -%>
      <%= action_list_item(t("events.upcoming"), root_path, "upcoming-events") %>
      <%= action_list_item(t("events.new"), new_event_path, "add-event") %>
    <% end -%>
  </section>
</aside>