config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :users

  resources :events do
    post :check, on: :collection
    post :check, on: :member

    get :register, to: "registrations#new"
    post :register, to: "registrations#create"

    resource  :registration, only: [:show, :update] do
      get :summary
    end
    resource :itinerary do
      post :check
    end
    resources :registrations, shallow: true
    resource  :timetable
    resources :activities
    resources :activity_types, only: [:create, :update, :destroy]
    resources :time_slots, only: [:create, :destroy]
    resources :scheduled_activities, only: [:create, :update, :destroy]
    resources :locations
    resources :payments do
      post :approve, on: :collection
      post :decline, on: :collection
    end
    resources :participants do
      resource :itinerary do
        post :check
      end
    end
    
    post "payments/:id", to: "payments#show" # PayPal POSTs this request
    
    resource  :account
    resource  :map, only: :show
  end
  
  post "events/:event_id/payments/:id/process",
    to: "payments#process_external_payment",
    as: :process_external_payment

  root to: "events#index"
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :registration, inverse_of: :payments
  has_one :event, through: :registration
  has_one :user, through: :registration

  enum state: [:pending, :approved, :declined, :refunded]

  monetize :amount_cents, numericality: { greater_than: 0 }

  scope :paid, -> { where(state: :approved) }
  scope :for_event, ->(event) {
    includes(:registration => :user)
      .where("registrations.event_id = ?", event.id)
      .references(:registrations)
  }

  before_validation :generate_token

  validates :payment_method_name, :token,
    presence: { allow_blank: false }

  def payment_method
    registration.event.payment_method(payment_method_name)
  end

  def payment_method=(payment_method)
    self.payment_method_name = payment_method.class.name.demodulize.underscore
  end

  def approve!
    update(state: :approved)
  end

  def decline!
    update(state: :declined)
  end

  protected

  def generate_token
    loop do
      self.token = SecureRandom.hex(32)
      break unless self.class.exists? token: token
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!, except: [:process_external_payment]
  before_action :ensure_registered, only: [:show, :new, :create]
  before_action :load_payment, only: [:show, :edit, :update, :destroy]

  skip_before_action :verify_authenticity_token, if: :processing_external_payment?

  def index
    authorize!(:update, event)
    @payment_methods = event.payment_methods.map.with_object({}) { |type, hash| hash[type.name] = type }
    @payments = ListPayments.new(event, params).call

    respond_to do |format|
      format.html
      format.json do
        render(json: @payments,
          serializer: PaginatedSerializer,
          each_serializer: PaymentSerializer,
          adapter: :json
        )
      end
    end
  end

  def show
    authorize!(:read, @payment)
    render("payments/#{@payment.payment_method_name}/#{@payment.state}")
  end

  def new
    registration.payments.select(&:pending?).map(&:destroy)
    @payment = blank_payment
  end

  def create
    Payment.transaction do
      @payment = blank_payment
      create_payment = CreatePayment.new(@payment, payment_method)
        .on(:pending, :approved) { |payment| redirect_to(event_payment_path(event, payment)) }
        .on(:redirect) { |url| redirect_to(url) }
        .on(:failure) { render(:new) }
      create_payment.call
    end
  end

  def approve
    authorize!(:update, event)
    approve = ApprovePayments.new(event, params[:payment_ids] || [])
    approve.call
    render(json: approve.payments, each_serializer: PaymentSerializer)
  end

  def decline
    authorize!(:update, event)
    decline = DeclinePayments.new(event, params[:payment_ids] || [])
    decline.call
    render(json: decline.payments, each_serializer: PaymentSerializer)
  end

  def process_external_payment
    ProcessExternalPayment.new(params.permit!).call
    render nothing: true
  end

  protected
  
  def processing_external_payment?
    (action_name == "process_external_payment") ||
    (request.post? && action_name == "show")
  end
  
  def load_payment
    @payment = event.payments.find(params[:id])
  end

  def event
    @event ||= begin
      event = Event.with_payment_details.find_by!(slug: params[:event_id])
      EventPresenter.new(event)
    end
  end

  def registration
    return nil unless signed_in?

    @presenter ||= begin
      @registration = event.registrations.with_packages.with_payments
        .find_by(user_id: current_user.id)
      @registration && RegistrationPresenter.new(@registration)
    end
  end

  def ensure_registered
    redirect_to(event_register_path(event)) unless registration.present?
  end

  def payment_params
    params.require(:payment).permit(:payment_method_name) if params[:payment].present?
  end

  def blank_payment
    @registration.payments.build(payment_params || {}).tap do |payment|
      payment.amount = registration.outstanding_balance if payment.amount.to_i.zero?
      payment.payment_method_name ||= event.payment_methods.first.name
    end
  end
  
  def payment_method
    event.payment_methods.detect { |m| m.name == @payment.payment_method_name }
  end
  
  helper_method :event, :registration, :payment_method
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_payment.html.erb
<%= content_tag(:tr, "data-id" => payment.id, "data-state" => payment.state) do %>
  <td>
    <input type="checkbox">
  </td>
  <td>
    <%= content_tag :span, payment.registration.user.name, class: "name" %>
    <%= mail_to payment.registration.user.email %>
  </td>
  <td>
    <%= l(payment.created_at.to_date, format: :short) %>
  </td>
  <td>
    <%= dollar_amount(payment.amount) %>
  </td>
  <td>
    <%= t("payment_methods.#{payment.payment_method_name}.name") %>
  </td>
  <td rel="state">
    <%= t("payments.state.#{payment.state}") %>
  </td>
<% end -%>

app/views/payments/index.html.erb
<div class="payments-list">
  <header>
    
  </header>
  <div class="table-container">
    <div class="table-and-footer" id="table">
      <div class="scrolling-table">
        <table>
          <thead>
            <tr>
              <th><input type="checkbox" name="select_all"></th>
              <th><%= User.human_attribute_name(:name) %></th>
              <th><%= Payment.human_attribute_name(:created_at) %></th>
              <th><%= Payment.human_attribute_name(:amount) %></th>
              <th><%= Payment.human_attribute_name(:payment_method_name) %></th>
              <th><%= Payment.human_attribute_name(:state) %></th>
            </tr>
          </thead>
          <tbody>
            <%= render(@payments) %>
          </tbody>
        </table>
      </div>
      <footer>
        <div class="buttons">
          <button rel="approve">
            <%= icon :ok %>
            <span><%= t("payments.approve") %></span>
          </button>
          <button rel="decline">
            <%= icon :cancel %>
            <span><%= t("payments.decline") %></span>
          </button>
        </div>
        <%= will_paginate @payments, inner_window: 2, outer_window: 0 %>
      </footer>
    </div>
  </div>
</div>

app/views/payments/new.html.erb
<% if registration.paid? %>
  <h1><%= t("payments.paid_in_full.title") %></h1>
  <p><%= t("payments.paid_in_full.message", event: event.name, link: edit_event_itinerary_path(event)).html_safe %></p>
<% else %>
  <h1><%= t("payments.complete_payment.title") %></h1>
  <p><%= t("payments.complete_payment.message", event: event.name, amount: dollar_amount(registration.outstanding_balance)).html_safe %></p>

  <%= form_for @payment, url: event_payments_path(event) do |form| %>
    <ul class="fancy-checkbox-list payment-methods">
      <% event.payment_methods.select(&:enabled?).each do |payment_method| -%>
        <li>
          <%= form.radio_button :payment_method_name, payment_method.name, required: true %>
          <%= form.label :payment_method_name, value: payment_method.name do -%>
            <%= inline_svg "icons/check.svg", class: "checkbox" %>
            <div class="details">
              <h4><%= t("payment_methods.#{payment_method.name}.name") %></h4>
              <p><%= t("payment_methods.#{payment_method.name}.description") %></p>
            </div>
          <% end -%>
        </li>
      <% end -%>
    </ul>

    <section class="buttons">
      <%= form.button do -%>
        <%= content_tag :span, t("registrations.continue") %>
        <%= icon "arrow-right" %>
      <% end -%>
    </section>
  <% end -%>
<% end %>